# Sample .travis.yml for R projects
language: r
cache: packages
sudo: required

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

warnings_are_errors: false
notifications:
  on_success: change
  on_failure: change

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes"
    - R_CHECK_ARGS="--no-build-vignettes --as-cran"
