// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// diff_table_cpp
NumericMatrix diff_table_cpp(NumericMatrix env_dat);
RcppExport SEXP bbgdm_diff_table_cpp(SEXP env_datSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type env_dat(env_datSEXP);
    __result = Rcpp::wrap(diff_table_cpp(env_dat));
    return __result;
END_RCPP
}
