// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// diff_table_cpp
NumericMatrix diff_table_cpp(NumericMatrix env_dat);
RcppExport SEXP bbgdm_diff_table_cpp(SEXP env_datSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type env_dat(env_datSEXP );
        NumericMatrix __result = diff_table_cpp(env_dat);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
