// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// diff_table_cpp
NumericMatrix diff_table_cpp(NumericMatrix env_dat);
RcppExport SEXP bbgdm_diff_table_cpp(SEXP env_datSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type env_dat(env_datSEXP);
    __result = Rcpp::wrap(diff_table_cpp(env_dat));
    return __result;
END_RCPP
}
// pred_bbgdm_cpp
NumericMatrix pred_bbgdm_cpp(NumericVector raster_stack, NumericMatrix output_raster, NumericMatrix neighbourhood, NumericVector bbgdm_coef);
RcppExport SEXP bbgdm_pred_bbgdm_cpp(SEXP raster_stackSEXP, SEXP output_rasterSEXP, SEXP neighbourhoodSEXP, SEXP bbgdm_coefSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type raster_stack(raster_stackSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type output_raster(output_rasterSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type neighbourhood(neighbourhoodSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bbgdm_coef(bbgdm_coefSEXP);
    __result = Rcpp::wrap(pred_bbgdm_cpp(raster_stack, output_raster, neighbourhood, bbgdm_coef));
    return __result;
END_RCPP
}
