# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

diff_table_cpp <- function(env_dat) {
    .Call('bbgdm_diff_table_cpp', PACKAGE = 'bbgdm', env_dat)
}

